### ISSUE TITLE
一日见闻 [2016.02.19] 

### ISSUE THREAD

**Issue by peterzd** [souche-hero/ruby-daily#7]
## ruby GIL及对多线程的处理

这篇[博客](http://www.rubyinside.com/does-the-gil-make-your-ruby-code-thread-safe-6051.html) 进行了一个比较详细的说明。对于直接使用`Thread.new`时产生的race condition，以及如何解决这个问题的一些方法，如`Mutex`，或者是`Queue`。在进行多线程编程时，也要注意操作符的使用，像`||=`这种其实不是一个atomic的操作，也会产生竞争，导致一些意想不到的问题

**Comment by 42thcoder** [comment]
学习下~
